from typing import List, Literal, TypedDict, Annotated, Optional, Dict, Any

class Speech(TypedDict):
    """
    Data structure for a single speech act.

    Attributes:
        round: The current round number
        seq: Sequence number within the round
        player_id: ID of the player who spoke
        content: LLM-generated speech content
        ts: Timestamp in milliseconds
    """

    round: int
    seq: int
    player_id: str
    content: str
    ts: int


class Vote(TypedDict):
    """
    Represents a single vote cast by a player.

    Vote Target Generation Logic:
    - Primary: LLM-generated through llm_decide_vote() based on:
      * Player's assigned word
      * Self-belief (role and confidence)
      * Suspicions about other players
      * Current round speeches and game state
    - Fallback: If LLM returns invalid vote (target not in alive players or None when abstain not allowed):
      * Use suspicions with the highest confidence
      * Otherwise select first available player

    The 'ts' and 'phase_id' are system-generated metadata.

    Attributes:
        target: The player ID being voted for
        ts: Timestamp of the vote, generated by the system (excluded from serialization)
        phase_id: The phase ID in which the vote was cast, generated by the system (excluded from serialization)
    """

    target: str
    ts: int
    phase_id: str

class SelfBelief(TypedDict):
    """
    Represents a player's belief about their own role.

    Attributes:
        role: The player's believed role (civilian or spy)
        confidence: Confidence level in the belief (0.0 to 1.0)
    """

    role: Literal["civilian", "spy"]
    confidence: float


class Suspicion(TypedDict):
    """
    Represents a player's suspicion about another player's role.

    Attributes:
        role: The suspected role (civilian or spy)
        confidence: Confidence level in the suspicion (0.0 to 1.0)
        reason: Reasoning behind the suspicion
    """

    role: Literal["civilian", "spy"]
    confidence: float
    reason: str

class PlayerMindset(TypedDict):
    """
    Represents a player's complete mental state including self-belief and suspicions.

    Attributes:
        self_belief: The player's belief about their own role
        suspicions: Dictionary mapping player_id to Suspicion objects
    """

    self_belief: SelfBelief
    suspicions: Dict[str, Suspicion]

class PlayerPrivateState(TypedDict):
    """
    Schema for a player's private state, largely managed by the LLM.

    Attributes:
        assigned_word: The word assigned to this player
        playerMindset: The player's mental state including self-belief and suspicions
    """

    assigned_word: str
    playerMindset: PlayerMindset


class HostPrivateState(TypedDict):
    """
    Host's private state containing invariant game setup information.

    Attributes:
        player_roles: Dictionary mapping player_id to role (civilian or spy)
        civilian_word: The word assigned to civilians
        spy_word: The word assigned to spies
    """

    player_roles: Dict[str, Literal["civilian", "spy"]]
    civilian_word: str
    spy_word: str